source 'https://rubygems.org'

gem 'registration', :path => 'components/registration', direct: true
gem 'service', :path => 'components/service', direct: true
gem 'admin', :path => 'components/admin', direct: true

gem 'registration_data', :path => 'components/registration_data'
gem 'service_data', :path => 'components/service_data'
