source 'https://rubygems.org'

gem 'registration', :path => 'components/registration', direct: true
gem 'service', :path => 'components/service', direct: true
gem 'admin', :path => 'components/admin', direct: true
