source 'https://rubygems.org'

gem 'registration', :path => 'components/registration', direct: true
gem 'service', :path => 'components/service', direct: true
gem 'admin_assets', :path => 'components/admin_assets'
